# Generated by Django 4.2.11 on 2024-04-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_alter_product_options_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collection_name',
            field=models.CharField(max_length=255, verbose_name='collection'),
        ),
    ]
