# Generated by Django 4.2.11 on 2024-04-27 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0008_remove_order_unit_price_orderdetails_unit_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='image',
        ),
    ]
